# ---- Builder Stage ----
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci
RUN npm install -g @nestjs/cli

COPY . .


RUN npm run build

# ---- Production Stage ----
FROM node:18-alpine AS production
WORKDIR /app

RUN addgroup -g 1001 -S nodejs \
    && adduser -S nestjs -u 1001

COPY package*.json ./
RUN npm ci --omit=dev



USER nestjs
CMD ["node", "dist/main.js"]
